#############################################################################
# Makefile for building: QssEditor
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? 8? 14 23:45:15 2015
# Project:  QssEditor.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake CONFIG+=release -o Makefile QssEditor.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DNVER1=0 -DNVER2=5 -DNVER3=6 -DNVER_STRING="\"0.5.6\"" -DTARGET=QssEditor -DQT_USE_QSTRINGBUILDER -DSCINTILLA_QT -DSCI_LEXER -DSVNROOT_FOR_DOWNLOAD="\"http://sourceforge.net/p/qsseditor/code/HEAD/tree/trunk\"" -DHTTPROOT="\"http://sourceforge.net/p/qsseditor\"" -DDOWNLOADROOT="\"http://sourceforge.net/projects/qsseditor\"" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -Wextra -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lqscintilla2 -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		qsseditor.cpp \
		qscilexerqss.cpp \
		project.cpp \
		settings.cpp \
		searchandreplace.cpp \
		options.cpp \
		about.cpp moc_qsseditor.cpp \
		moc_searchandreplace.cpp \
		moc_options.cpp \
		moc_about.cpp \
		qrc_qsseditor.cpp
OBJECTS       = main.o \
		qsseditor.o \
		qscilexerqss.o \
		project.o \
		settings.o \
		searchandreplace.o \
		options.o \
		about.o \
		moc_qsseditor.o \
		moc_searchandreplace.o \
		moc_options.o \
		moc_about.o \
		qrc_qsseditor.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		QssEditor-common.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		QssEditor.pro
QMAKE_TARGET  = QssEditor
DESTDIR       = 
TARGET        = QssEditor

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_qsseditor.h ui_searchandreplace.h ui_options.h ui_about.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	lupdate -no-obsolete /home/songjiexu/software/qsseditor-0.5.6/QssEditor.pro -ts /home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_de.ts /home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_en.ts /home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_ro.ts /home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_ru.ts /home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_zh_CN.ts
	 lrelease "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_de.ts" -qm "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_de.qm"
	 lrelease "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_en.ts" -qm "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_en.qm"
	 lrelease "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_ro.ts" -qm "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_ro.qm"
	 lrelease "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_ru.ts" -qm "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_ru.qm"
	 lrelease "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_zh_CN.ts" -qm "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_zh_CN.qm"
	 test -d "/home/songjiexu/software/qsseditor-0.5.6/translations" || mkdir -p "/home/songjiexu/software/qsseditor-0.5.6/translations"
	 $(COPY) "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_de.qm" "/home/songjiexu/software/qsseditor-0.5.6/translations"
	 $(COPY) "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_en.qm" "/home/songjiexu/software/qsseditor-0.5.6/translations"
	 $(COPY) "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_ro.qm" "/home/songjiexu/software/qsseditor-0.5.6/translations"
	 $(COPY) "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_ru.qm" "/home/songjiexu/software/qsseditor-0.5.6/translations"
	 $(COPY) "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_zh_CN.qm" "/home/songjiexu/software/qsseditor-0.5.6/translations"
	

Makefile: QssEditor.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		QssEditor-common.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) CONFIG+=release -o Makefile QssEditor.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
QssEditor-common.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) CONFIG+=release -o Makefile QssEditor.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QssEditor0.5.6 || $(MKDIR) .tmp/QssEditor0.5.6 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QssEditor0.5.6/ && $(COPY_FILE) --parents qsseditor.h qscilexerqss.h project.h settings.h searchandreplace.h options.h about.h tools.h .tmp/QssEditor0.5.6/ && $(COPY_FILE) --parents qsseditor.qrc .tmp/QssEditor0.5.6/ && $(COPY_FILE) --parents main.cpp qsseditor.cpp qscilexerqss.cpp project.cpp settings.cpp searchandreplace.cpp options.cpp about.cpp .tmp/QssEditor0.5.6/ && $(COPY_FILE) --parents qsseditor.ui searchandreplace.ui options.ui about.ui .tmp/QssEditor0.5.6/ && $(COPY_FILE) --parents /home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_de.ts /home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_en.ts /home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_ro.ts /home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_ru.ts /home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_zh_CN.ts .tmp/QssEditor0.5.6/ && (cd `dirname .tmp/QssEditor0.5.6` && $(TAR) QssEditor0.5.6.tar QssEditor0.5.6 && $(COMPRESS) QssEditor0.5.6.tar) && $(MOVE) `dirname .tmp/QssEditor0.5.6`/QssEditor0.5.6.tar.gz . && $(DEL_FILE) -r .tmp/QssEditor0.5.6


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


tag:
	echo 0.5.6> "/home/songjiexu/software/qsseditor-0.5.6/QssEditor-version.tag"
	 svn -m "0.5.6 file tag" commit "/home/songjiexu/software/qsseditor-0.5.6/QssEditor-version.tag"
	 svn -m "0.5.6 tag" copy "svn+ssh://dmitrykx@svn.code.sf.net/p/qsseditor/code/trunk" "svn+ssh://dmitrykx@svn.code.sf.net/p/qsseditor/code/tags/0.5.6"
	

distsrc:
	if exist "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-0.5.6" rd /S /Q "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-0.5.6"
	 svn export /home/songjiexu/software/qsseditor-0.5.6 "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-0.5.6"
	 del /F /Q qsseditor-0.5.6.zip
	 /usr/bin/7z a -r -tzip -mx=9 qsseditor-0.5.6.zip "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-0.5.6"
	 rd /S /Q "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-0.5.6"
	

distbin:
	if exist "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6" rd /S /Q "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6"
	 mkdir "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6"
	 mkdir "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6/platforms"
	 mkdir "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6/imageformats"
	 mkdir "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6/translations"
	 copy /y "/home/songjiexu/software/qsseditor-0.5.6/$(DESTDIR_TARGET)" "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6"
	 copy /y "/usr/lib/x86_64-linux-gnu/qt4/bin\QtCore4.dll" "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6"
	 copy /y "/usr/lib/x86_64-linux-gnu/qt4/bin\QtGui4.dll" "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6"
	 copy /y "/usr/bin\libgcc_s_seh-1.dll" "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6"
	 copy /y "/usr/bin\libwinpthread-1.dll" "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6"
	 copy /y "/usr/bin\libstdc++-6.dll" "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6"
	 copy /y "/usr/lib/x86_64-linux-gnu/qt4/plugins\imageformats\qico4.dll" "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6/imageformats"
	 copy /y "/usr/lib/x86_64-linux-gnu/qt4/plugins\imageformats\qjpeg4.dll" "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6/imageformats"
	 copy /y "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_de.qm" "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6/translations"
	 copy /y "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_en.qm" "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6/translations"
	 copy /y "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_ro.qm" "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6/translations"
	 copy /y "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_ru.qm" "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6/translations"
	 copy /y "/home/songjiexu/software/qsseditor-0.5.6/ts/qsseditor_zh_CN.qm" "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6/translations"
	 copy /y "/usr/share/qt4/translations\qt_de.qm" "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6/translations"
	 copy /y "/usr/share/qt4/translations\qt_ru.qm" "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6/translations"
	 copy /y "/usr/share/qt4/translations\qt_zh_CN.qm" "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6/translations"
	 copy /y "/home/songjiexu/software/qsseditor-0.5.6\LICENSE.txt" "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6"
	 del /F /Q qsseditor-standalone-0.5.6-x86_64.zip
	 /usr/bin/7z a -r -tzip -mx=9 qsseditor-standalone-0.5.6-x86_64.zip "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6"
	 rd /S /Q "/home/songjiexu/software/qsseditor-0.5.6/qsseditor-standalone-0.5.6"
	

check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qsseditor.cpp moc_searchandreplace.cpp moc_options.cpp moc_about.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qsseditor.cpp moc_searchandreplace.cpp moc_options.cpp moc_about.cpp
moc_qsseditor.cpp: project.h \
		qsseditor.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) qsseditor.h -o moc_qsseditor.cpp

moc_searchandreplace.cpp: searchandreplace.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) searchandreplace.h -o moc_searchandreplace.cpp

moc_options.cpp: options.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) options.h -o moc_options.cpp

moc_about.cpp: about.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) about.h -o moc_about.cpp

compiler_rcc_make_all: qrc_qsseditor.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qsseditor.cpp
qrc_qsseditor.cpp: qsseditor.qrc \
		images/user.png \
		images/close.png \
		images/battery.png \
		images/image-sunset.png \
		images/save.png \
		images/redo.png \
		images/qsseditor.ico \
		images/undo.png \
		images/saveas.png \
		images/open.png \
		images/options.png \
		images/flags/en.png \
		images/flags/ro.png \
		images/flags/de.png \
		images/flags/ru.png \
		images/flags/zh_CN.png
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name qsseditor qsseditor.qrc -o qrc_qsseditor.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_qsseditor.h ui_searchandreplace.h ui_options.h ui_about.h
compiler_uic_clean:
	-$(DEL_FILE) ui_qsseditor.h ui_searchandreplace.h ui_options.h ui_about.h
ui_qsseditor.h: qsseditor.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic qsseditor.ui -o ui_qsseditor.h

ui_searchandreplace.h: searchandreplace.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic searchandreplace.ui -o ui_searchandreplace.h

ui_options.h: options.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic options.ui -o ui_options.h

ui_about.h: about.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic about.ui -o ui_about.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp qsseditor.h \
		project.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qsseditor.o: qsseditor.cpp searchandreplace.h \
		qscilexerqss.h \
		qsseditor.h \
		project.h \
		settings.h \
		options.h \
		tools.h \
		about.h \
		ui_qsseditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qsseditor.o qsseditor.cpp

qscilexerqss.o: qscilexerqss.cpp qscilexerqss.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qscilexerqss.o qscilexerqss.cpp

project.o: project.cpp project.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o project.o project.cpp

settings.o: settings.cpp settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

searchandreplace.o: searchandreplace.cpp searchandreplace.h \
		settings.h \
		ui_searchandreplace.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o searchandreplace.o searchandreplace.cpp

options.o: options.cpp settings.h \
		options.h \
		ui_options.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o options.o options.cpp

about.o: about.cpp about.h \
		tools.h \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o about.cpp

moc_qsseditor.o: moc_qsseditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qsseditor.o moc_qsseditor.cpp

moc_searchandreplace.o: moc_searchandreplace.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_searchandreplace.o moc_searchandreplace.cpp

moc_options.o: moc_options.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_options.o moc_options.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

qrc_qsseditor.o: qrc_qsseditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qsseditor.o qrc_qsseditor.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

